# Generated by Django 3.0.8 on 2020-07-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRISPR_DATABASE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CRISPR', models.TextField(blank=True, null=True, verbose_name='CRISPR 序列')),
                ('CRISPR_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='CRISPR 名字')),
                ('PI', models.TextField(blank=True, null=True, verbose_name='PI 序列')),
                ('CRISPR_type', models.CharField(blank=True, choices=[('一型', '第一种类型'), ('二型', '第二种类型'), ('三型', '第三种类型'), ('四型', '第四种类型')], max_length=50, null=True, verbose_name='CRISPR 类型 ')),
                ('PAM', models.CharField(blank=True, max_length=50, null=True, verbose_name='PAM 序列')),
            ],
            options={
                'verbose_name': 'CRISPR',
                'verbose_name_plural': 'CRISPR',
            },
        ),
    ]
